spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/paradise
    driver-class-name: org.h2.Driver
    username: sa
    password:

